- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- add badges to readme
- add pr template
> docs: add badges to readme

- .github/workflows/common-golang-ci.yml
fix the format of docker image tag in common-golang-ci workflow
> fix: fix the format of docker image tag in common-golang-ci workflow

- renovate.json
Add a description to the renovate schedule rule.
> docs: add a description to the renovate schedule rule

- renovate.json
fix missing comma from renovate.json
> ci: fix missing comma from renovate.json

- .github/workflows/common-terraform-module-ci.yml
Moving tests out into a separate job so they can be run independently. 
> feat: split to multiple jobs

- .github/workflows/common-terraform-module-ci.yml
add support for logdna ingestion key
> feat: add support for logdna ingestion key

- .github/workflows/common-terraform-module-ci.yml
Replace this text with a summary of the changes in this PR. Include why the changes are needed and context about the changes. List required dependencies.
---
> ci: dont run cra if no target

- .github/workflows/release.yml
ci: update release.yml - lock into main branch to avoid circular dependency
---
> ci: update release.yml - lock into main branch to avoid circular dependency

- .github/workflows/common-terraform-module-ci.yml
set missing ownership in Infrastructure Test stage of common terraform pipeline
---
> fix: set missing ownership in Infrastructure Test stage of common terraform pipeline

- .github/workflows/ci.yml
- .github/workflows/common-golang-ci.yml
- .github/workflows/common-release.yml
- .github/workflows/common-terraform-module-ci.yml
`NO_CONTAINER` is no longer needed by the Makefile.
`TF_VAR_ibmcloud_api_key_ext` is needed by terraform-ibm-transit-gateway test
---
> feat: Remove NO_CONTAINER and add TF_VAR_ibmcloud_api_key_ext env vars

- .github/workflows/common-terraform-module-ci.yml
Only install CRA if not already installed
---
> fix: Only install CRA if not already installed

- .github/workflows/ci.yml
- .secrets.baseline
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …
> ci: fix indentation error

- .github/settings.yml
update context
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the …
> ci: Update settings.yml

- .github/settings.yml
- .github/workflows/ci-pipeline.yml
- .github/workflows/ci.yml
- .github/workflows/common-golang-ci.yml
- .github/workflows/common-release.yml
- .github/workflows/common-terraform-module-ci-v2.yml
- .github/workflows/common-terraform-module-ci.yml
- .github/workflows/post-usage.yml
- .github/workflows/release.yml
- .github/workflows/terraform-test-pipeline.yml
- .secrets.baseline
refactoring pipelines
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of …
> Pipeline refactor

- .github/workflows/common-terraform-module-ci.yml
If a release is required, replace this text with information that users need to know about the release. Write the release notes to help users understand the changes, and include information about how to update from the previous version. 
Your notes helps the merger write the commit message for the PR that is published in the release notes for the module.
---
- Use a relevant [conventional …
> fix: remove needs

- .github/workflows/common-terraform-module-ci-v2.yml
- Update to use FS Cloud 1.2 Profile
---
- Use a relevant [conventional commit](https://www.conventionalcommits.org/) message that is based on the PR contents and any release notes provided by the PR author. The commit message determines whether a new version of the module is needed, and if so, which semver increment to use (major, minor, or patch).
> ci: update profile to 1.2

- .github/workflows/ci-pipeline.yml
- .github/workflows/common-terraform-module-ci.yml
renovate sweeper is no longer needed as it has been replaced by the `postUpgradeTasks` defined in [commonRenovateConfig.json](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/commonRenovateConfig.json)
feat: remove renovate sweeper from pipeline as it has been replaced by the `postUpgradeTasks` defined in [commonRenovateConfig.json](https://github.com/terraform-ibm-modules/common-dev-assets/blob/main/commonRenovateConfig.json)
Run the CI pipeline when …
> feat: remove renovate sweeper from pipeline

- .github/settings.yml
Added "core-team" topic to .github/settings.yml 
Run the CI pipeline when the PR is ready for review and you expect …
> Add core-team topic to repo

- README.md
remove "Build Status" badge from docs 
Run the CI pipeline when the PR is ready for review and you expect tests to pass. …
> docs: remove "Build Status" badge from docs

- .github/workflows/common-terraform-module-ci.yml
update default CRA SCC profile to FSCloud 1.3.0
Run the CI pipeline when the PR is ready for review and you expect tests …
> feat: update default CRA SCC profile to FSCloud 1.3.0

- .github/workflows/terraform-test-pipeline.yml
If the CI pipeline doesn't run when you …
> fix: fix bug in CRA config logic

- .github/workflows/terraform-test-pipeline.md
If the CI pipeline doesn't run when you …
> docs: update CRA doc comment

- .github/workflows/common-terraform-module-ci-v2.yml
- .github/workflows/terraform-test-pipeline.md
- .github/workflows/terraform-test-pipeline.yml
- .secrets.baseline
CRA will now use SCC instances api instead of deprecated account api + default CRA profile is now FSCloud 1.3.0 for v2 pipeline
- CRA will now use SCC instances api instead of deprecated account api
- default CRA profile is now FSCloud 1.3.0 for v2 pipeline
```
/run pipeline
```
- Use a relevant [conventional …
> feat: CRA will now use SCC instances api instead of deprecated account api + default CRA profile is now FSCloud 1.3.0 for v2 pipeline

- .github/workflows/ci.yml
Reverts terraform-ibm-modules/common-pipeline-assets#627
> Revert "add label job"

- .github/workflows/ci.yml
> add label job

- .github/workflows/ci.yml
- .github/workflows/terraform-test-pipeline.md
- .github/workflows/terraform-test-pipeline.yml
Adds the option to specify the toolchain id for cra in the config file
```
/run pipeline
```
> Cra toolchain config

- .github/workflows/common-release.yml
> add extra echo to help debug

- README.md
Generate a release
```
/run pipeline
```
> fix: format readme

- .github/workflows/common-release.yml
> fix: update command

- .github/workflows/common-release.yml
- .github/workflows/release.yml
maybe this one also creates the prompt.. it defaults to if asked so I am explicitly disableing it
```
/run pipeline
```
> fix: disable tag sign

- .github/workflows/common-release.yml
- .github/workflows/release.yml
Running the update outside of the container and setting the GPG details after the release fixes the pipeline. 
```
/run pipeline
```
> Update workflow to run outside container

- .github/workflows/create-gh-issue-and-slack-message.yml
Pipeline fail issue title has been updated to have a time as well as date.
```
/run pipeline
```
> Add time to pipeline fail issue title

- .github/workflows/pages-release.yml
Creating release pipeline action for https://github.com/terraform-ibm-modules/landing-zone-config-tool. 
```
/run pipeline
```
> feat: add pages release action

- .github/workflows/post-usage.yml
replace `ORG_READER_GH_TOKEN` with `GITHUB_TOKEN`
```
/run pipeline
```
> replace `ORG_READER_GH_TOKEN` with `GITHUB_TOKEN`

- .github/workflows/post-usage.yml
Reverts terraform-ibm-modules/common-pipeline-assets#693
> Revert "replace `ORG_READER_GH_TOKEN` with `GITHUB_TOKEN`"

- .github/workflows/post-usage.yml
> docs: add some code comments

- .github/workflows/post-usage.yml
- Improvised the error logging seen as part of a job
```
/run pipeline
```
> refactor: improved logging

- .github/workflows/ci.yml
- .github/workflows/common-golang-ci.yml
- .github/workflows/common-terraform-module-ci-v2.yml
- .github/workflows/post-usage.yml
To start workflow, `/run pipeline` command is also supported to include a space in the command i.e. `/run pipeline `
This PR addresses [Issue-9252](https://github.ibm.com/GoldenEye/issues/issues/9252) and [Issue-9346](https://github.ibm.com/GoldenEye/issues/issues/9346)
- Enhanced the workflow trigger logic to consider a trailing space in the pipeline execution command.
- Improved error logging for `Notify-Contributor-Requirements` Job.
```
/run pipeline
```
- Use a conventional commit message to set the release level. Follow the …
> feat: added support for trailing spaces in pipeline run command

- .github/workflows/terraform-test-pipeline.md
- .github/workflows/terraform-test-pipeline.yml
Removal of logDNA references are addressed.
Issue Reference - [Issue-10955](https://github.ibm.com/GoldenEye/issues/issues/10955)
```
/run pipeline
```
> doc: removed logdna references

- .github/workflows/common-python-ci.yml
> feat: add Python CI workflow with customizable inputs and steps

- .github/workflows/common-python-ci.yml
> fix: fix python workflow
